#DB接続方法
#ActiveRecord::Base.configurations = YAML.load_file('database.yml')
#ActiveRecord::Base.establish_connection('development')の代わり

development:
adapter: mysql2
database: line_app
host: 127.0.0.1
username: root
password: kur0@line
encoding: utf8
pool: 5
